# Generated by Django 3.0.3 on 2020-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_auto_20200316_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=15)),
                ('status', models.CharField(blank=True, choices=[['None', 'None'], ['picked', 'picked'], ['on the way', 'on the way'], ['delivered', 'delivered']], default=None, max_length=30, null=True)),
                ('currentorder', models.ManyToManyField(to='service.Order')),
            ],
        ),
    ]
