# Generated by Django 3.0.3 on 2020-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
