# Generated by Django 3.0.3 on 2020-03-16 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default=None, max_length=30, null=True, unique=True)),
                ('hotel_address', models.CharField(default=None, max_length=100, null=True)),
                ('hotel_phone_number', models.CharField(max_length=20)),
                ('hotel_reting', models.IntegerField(default=0, null=True)),
                ('hoel_image', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(max_length=20)),
                ('item_ids', models.CharField(max_length=500)),
                ('order_date', models.DateField(default=datetime.datetime.now)),
                ('hotel_status', models.CharField(choices=[['accept', 'accept'], ['processing', 'processing'], ['cooking', 'cooking'], ['packed', 'packed'], ['delivered', 'delivered']], max_length=30)),
                ('user_hotel_reting', models.IntegerField(null=True)),
                ('user_delivery_boy_reting', models.IntegerField(null=True)),
                ('user_review', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.IntegerField(default=0, null=True)),
                ('item_discount', models.IntegerField(default=0, null=True)),
                ('item_image', models.CharField(default=None, max_length=1000, null=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Hotel', to_field='hotel_name')),
            ],
        ),
    ]
