# Generated by Django 3.0.7 on 2020-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200316_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hotel_status',
            field=models.CharField(choices=[['cancel', 'cancel'], ['accept', 'accept'], ['processing', 'processing'], ['cooking', 'cooking'], ['packed', 'packed'], ['delivered', 'delivered'], ['orderonhandofdelvboy', 'orderonhandofdelvboy']], default='Please Wait for Hotel conformation !', max_length=30),
        ),
    ]
