# Generated by Django 3.0.7 on 2020-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200627_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='hotel_status',
            field=models.CharField(choices=[['cancel', 'cancel'], ['accept', 'accept'], ['processing', 'processing'], ['cooking', 'cooking'], ['packed', 'packed'], ['delivered', 'delivered'], ['orderonhandofdelvboy', 'orderonhandofdelvboy'], ['On the Way', 'On the Way'], ['iod', 'iod'], ['Delivered', 'Delivered']], default='Please Wait for Hotel conformation !', max_length=30),
        ),
    ]
