# Generated by Django 3.0.7 on 2020-06-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200628_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='None', max_length=500, null=True),
        ),
    ]
